### PR TITLE
[WIP] Replaced to_a processing to improve Cumo's performance.

### PR DESCRIPTION
**Pull request by naitoh**
@sonots I replaced to_a processing to improve Cumo's performance. 
However, on the contrary, the performance at Cumo was degraded.
Do you know the reason for the performance degradation?

# GPU (Cumo)
## red-chainer master (2308e1db8f4ec99c0661a9a0ed7e5d0e1b14ebe6)

```
$ ruby examples/mnist/mnist.rb -e 1 -gpu 0
GPU: 0
# unit: 1000
# Minibatch-size: 100
# epoch: 1

epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  elapsed_time
1           0.194864    0.115074              0.941034       0.9636                    11.3586    
```

## red-chainer this pull request (38aa5f15014857bbe1512f274866a586bdcfe323)

```
$ ruby examples/mnist/mnist.rb -e 1 -gpu 0
GPU: 0
# unit: 1000
# Minibatch-size: 100
# epoch: 1

epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  elapsed_time
1           0.190484    0.0968807             0.942268       0.9686                    16.3715  
```

## Environment
* Ruby 2.6.0
* cumo-gpu server
* cumo master (983a2049832ded233014349b4983d02f7314c25c)

# CPU (Numo)
## red-chainer master (2308e1db8f4ec99c0661a9a0ed7e5d0e1b14ebe6)
```
$ ruby  -r numo/linalg/use/openblas examples/mnist/mnist.rb -e 1
GPU: -1
# unit: 1000
# Minibatch-size: 100
# epoch: 1

epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  elapsed_time
1           0.194983    0.120302              0.9401         0.9631                    28.5607     
```

## red-chainer this pull request (38aa5f15014857bbe1512f274866a586bdcfe323)
```
$ ruby  -r numo/linalg/use/openblas examples/mnist/mnist.rb -e 1
GPU: -1
# unit: 1000
# Minibatch-size: 100
# epoch: 1

epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  elapsed_time
1           0.192544    0.127859              0.94165        0.9595                    28.2767  
```

There is no performance degradation in the CPU environment.

## Environment
* CentOS 7.3.1611 (x86_64)
* Ruby 2.6.0
* numo-narray 0.9.1.4
* numo-linalg 0.1.4

### CODE REVIEW

**Comment by sonots** [comment]
thanks, I will take a look later.

**Comment by naitoh** [comment]
> However, on the contrary, the performance at Cumo was degraded.
> Do you know the reason for the performance degradation?

@sonots I'm sorry.
This is not a problem of cumo, it seems that the #at method of numo is slow.

https://github.com/ruby-numo/numo-narray/blob/master/lib/numo/narray/extra.rb#L67

```
$ benchmark-driver diagonal_at_fp32.yaml
Calculating -------------------------------------
a.at(Numo::Int32(X).seq.to_a, Numo::Int32(X).seq.to_a     3.756k i/s -     10.000k times in 2.662174s (266.22μs/i)
     b.at(Numo::Int32(X).seq,      Numo::Int32(X).seq    10.326k i/s -     10.000k times in 0.968468s (96.85μs/i)
                                           c.diagonal     2.106M i/s -     10.000k times in 0.004749s (474.91ns/i)

Comparison:
                                           c.diagonal:   2105680.3 i/s 
     b.at(Numo::Int32(X).seq,      Numo::Int32(X).seq:     10325.6 i/s - 203.93x  slower
a.at(Numo::Int32(X).seq.to_a, Numo::Int32(X).seq.to_a:      3756.3 i/s - 560.57x  slower
```

```
$ cat diagonal_at_fp32.yaml 
loop_count: 10000
prelude: |
  require 'numo/narray'
  X = 1000
  a = Numo::SFloat.new(X, X).seq(0)
  b = Numo::SFloat.new(X, X).seq(0)
  c = Numo::SFloat.new(X, X).seq(0)
  y = Numo::Int32.new(X).seq
  z = Numo::Int32.new(X).seq.to_a
  sleep 5

benchmark:
  'a.at(Numo::Int32(X).seq.to_a, Numo::Int32(X).seq.to_a' : a.at(z, z)
  'b.at(Numo::Int32(X).seq,      Numo::Int32(X).seq'      : b.at(y, y)
  'c.diagonal'                                            : c.diagonal
```

**Comment by sonots** [comment]
Let me close once.

**Comment by naitoh** [comment]
> Let me close once.

OK, Thanks.

**Pull request closed without merging**
